# -*- mode: ruby -*-
# vi: set ft=ruby :

## puts on a given vagrant command
def on_cmd_puts(cmd, msg)
  puts msg if ARGV[0] == cmd
end

## Notify the user when the haskell image is being downloaded
##   FIXME: is there a cleaner way to do this?
set_trace_func proc { |event, file, line, id, binding, classname|
  if event == 'call'
    if "#{classname}" == 'VagrantPlugins::DockerProvider::Action::Create' &&
       "#{id}"        == 'call'
       on_cmd_puts('up', 'container => docker    : downloading haskell image; please wait …')
     end
  end
}

VAGRANTFILE_API_VERSION      = '2'
Vagrant.require_version    '>=  1.6.3'

Vagrant.configure( VAGRANTFILE_API_VERSION ) do |cfg|

  ## needed to avoid 'No Host IP' error
  cfg.vm.synced_folder '.', '/vagrant', disabled: true

  cfg.vm.provider 'docker' do |dkr, ovr|

    ## customize the docker host
    dkr.vagrant_vagrantfile  = '../host/Vagrantfile'

    ## use the haskell docker image
    dkr.image                = 'darinmorrison/haskell:0.2.0'

    ## configure ssh according to phusion/baseimage
    ovr.ssh.username         = 'root'
    ovr.ssh.private_key_path = 'keys/insecure_key'

    ## start the container
    dkr.cmd                  = ['/sbin/my_init', '--enable-insecure-key']
    dkr.name                 = 'container-haskell-docker'
    dkr.volumes              = ['/vagrant/shared:/root/shared']

  end

end
